### ISSUE TITLE
Incorrectly calculated values for different types of variables

### ISSUE THREAD

**Issue by zzimagination** [Arc-huangjingtong/UniInk-CSharpInterpreter4AOT#2]
Code:
```
	public UniInk_Speed uniInk;

	// Start is called once before the first execution of Update after the MonoBehaviour is created
	void Start()
	{
		uniInk = new UniInk_Speed();
		uniInk.RegisterVariable( "Speed", InkValue.GetFloatValue( 10.0f ) );
		uniInk.RegisterVariable( "Time", InkValue.GetIntValue( 60 ) );
		var result = uniInk.Evaluate( "Speed * Time" ) as InkValue;
		Debug.Log( result.Value_float ); // result 0
	}
```
Result is 0.
Does Speed and Time have to be the same type？

**Comment by Arc-huangjingtong** [comment]
yes ， this is design ，you can change operator function and support it :-D。

**Comment by zzimagination** [comment]
> yes ， this is design ，you can change operator function and support it :-D。

ok, thanks.

**Comment by Arc-huangjingtong** [comment]
> > yes ， this is design ，you can change operator function and support it :-D。是的，这是设计，你可以更改操作员功能并支持它:-D。
> 
> ok, thanks. 好，谢谢。

Hi , I thought about it yesterday
now , uniInk will throw exception when operator different type values 

3Q your suggestion!
